// frontend/dashboard/components/integrations/donatello.tsx
import { ActionIcon, Alert, Anchor, CopyButton, Stepper, Text, TextInput } from '@mantine/core';
import { showNotification } from '@mantine/notifications';
import { IconCopy, IconDeviceFloppy, IconInfoCircle, IconLink } from '@tabler/icons';
import { useTranslation } from 'next-i18next';
import { Fragment, useEffect, useState } from 'react';

import { ManualComponent } from './manualComponent';

import { useDonatelloIntegration } from '@/services/api/integrations/donatello';

export default () => {
	const manager = useDonatelloIntegration();
	const { data: apiKey } = manager.useData();

	const [key, setKey] = useState<string>();

	const siteUrl = `${window.location.origin}/api/webhooks/integrations/donatello`;

	useEffect(() => {
		if (apiKey) {
			setKey(apiKey);
		}
	}, [apiKey]);


	return (
		<ManualComponent
			integrationKey={'donatello'}
			imageSize={50}
			body={
				<Stepper
					active={0}
					allowNextStepsSelect={false}
					orientation="vertical"
					w={'100%'}
					styles={{
						step: {
							width: '100%',
						},
						stepBody: {
							width: '100%',
						},
					}}
				>
					<Stepper.Step
						label="Step 1"
						description={
							<Fragment>
								Go to{' '}
								<Anchor href={'https://donatello.to/panel/settings'} target={'_blank'}>
									https://donatello.to/panel/settings
								</Anchor>{' '}
								and scroll to "Вихідний API" section
							</Fragment>
						}
					/>
					<Stepper.Step
						label="Step 2"
						description={
							<div>
								Copy api key and paste into "Api Key" input
								<TextInput
									mt={5}
									value={key}
									onChange={() => {}}
									variant={'filled'}
									rightSection={
										<CopyButton value={apiKey!}>
											{({ copy }) => (
												<ActionIcon
													onClick={() => {
														copy();
														showNotification({
															color: 'green',
															title: 'Copied',
															message: 'Copied to clipboard',
														});
													}}
												>
													<IconCopy />
												</ActionIcon>
											)}
										</CopyButton>
									}
								/>
							</div>
						}
					/>
					<Stepper.Step
						label="Step 3"
						description={
							<div>
								Copy link and paste into link field
								<TextInput
									styles={{
										input: {
											width: '100%',
										},
									}}
									mt={5}
									value={siteUrl}
									onChange={() => {}}
									variant={'filled'}
									rightSection={
										<CopyButton value={siteUrl!}>
											{({ copy }) => (
												<ActionIcon
													onClick={() => {
														copy();
														showNotification({
															color: 'green',
															title: 'Copied',
															message: 'Copied to clipboard',
														});
													}}
												>
													<IconCopy />
												</ActionIcon>
											)}
										</CopyButton>
									}
								/>
							</div>
						}
					/>
				</Stepper>
			}
		/>
	);
};

// web/layers/dashboard/components/integrations/donatello.vue
<script setup lang="ts">
import { ExternalLink } from 'lucide-vue-next'

import DonatelloSVG from '@/assets/integrations/donatello.svg?use'
import DonateDescription from '@/components/integrations/helpers/donateDescription.vue'
import WithSettings from '@/components/integrations/variants/withSettings.vue'
import { Alert, AlertDescription } from '@/components/ui/alert'
import CopyInput from '@/components/ui/copy-input/CopyInput.vue'
import { useIntegrationsPageData } from '@/api/integrations/integrations-page.ts'

const integrationsPage = useIntegrationsPageData()

const webhookUrl = `${window.location.origin}/api/webhooks/integrations/donatello`
</script>

<template>
	<WithSettings title="Donatello" :icon="DonatelloSVG" icon-width="48px">
		<template #description>
			<DonateDescription />
		</template>
		<template #settings>
			<div class="flex flex-col gap-6">
				<!-- Step 1 -->
				<div class="flex flex-col gap-2">
					<div class="flex items-center gap-2">
						<div
							class="flex h-8 w-8 items-center justify-center rounded-full bg-muted text-sm font-medium"
						>
							1
						</div>
						<h3 class="font-medium">Go to Donatello settings</h3>
					</div>
					<Alert>
						<AlertDescription class="flex items-center gap-2">
							<a
								href="https://donatello.to/panel/settings"
								target="_blank"
								rel="noopener noreferrer"
								class="inline-flex items-center gap-1 font-medium underline underline-offset-4"
							>
								https://donatello.to/panel/settings
								<ExternalLink class="h-4 w-4" />
							</a>
							and scroll to "Вихідний API" section
						</AlertDescription>
					</Alert>
				</div>

				<!-- Step 2 -->
				<div class="flex flex-col gap-2">
					<div class="flex items-center gap-2">
						<div
							class="flex h-8 w-8 items-center justify-center rounded-full bg-muted text-sm font-medium"
						>
							2
						</div>
						<h3 class="font-medium">Copy API key</h3>
					</div>
					<div class="flex flex-col gap-2 pl-10">
						<span class="text-sm text-muted-foreground"
							>Copy api key and paste into "Api Key" input</span
						>
						<CopyInput :text="integrationsPage.donatelloData.value?.integrationId ?? ''" />
					</div>
				</div>

				<!-- Step 3 -->
				<div class="flex flex-col gap-2">
					<div class="flex items-center gap-2">
						<div
							class="flex h-8 w-8 items-center justify-center rounded-full bg-muted text-sm font-medium"
						>
							3
						</div>
						<h3 class="font-medium">Set webhook URL</h3>
					</div>
					<div class="flex flex-col gap-2 pl-10">
						<span class="text-sm text-muted-foreground">Copy link and paste into "Link" field</span>
						<CopyInput :text="webhookUrl" />
					</div>
				</div>
			</div>
		</template>
	</WithSettings>
</template>
