// frontend/dashboard/pages/integrations.tsx
import { Grid } from '@mantine/core';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import dynamic from 'next/dynamic';

import { DonationAlertsIntegration } from '../components/integrations/donationalerts';
import { LastfmIntegration } from '../components/integrations/lastfm';
import { SpotifyIntegration } from '../components/integrations/spotify';
import { StreamlabsIntegration } from '../components/integrations/streamlabs';
import { VKIntegration } from '../components/integrations/vk';

import { DonatePayIntegration } from '@/components/integrations/donatepay';
import { FaceitIntegration } from '@/components/integrations/faceit';
import { ValorantIntegration } from '@/components/integrations/valorant';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
export const getServerSideProps = async ({ locale }) => ({
	props: {
		...(await serverSideTranslations(locale, ['integrations', 'layout', 'common'])),
	},
});

const cols = {
	xs: 12,
	sm: 12,
	md: 5,
	lg: 5,
	xl: 5,
};

const DonateStreamIntegration = dynamic(() => import('../components/integrations/donateStream'), {
	ssr: false,
});

const DonatelloIntegration = dynamic(() => import('../components/integrations/donatello'), {
	ssr: false,
});

export default function Integrations() {
	return (
		<Grid justify="center">
			<Grid.Col {...cols}>
				<SpotifyIntegration />
			</Grid.Col>
			<Grid.Col {...cols}>
				<LastfmIntegration />
			</Grid.Col>
			<Grid.Col {...cols}>
				<VKIntegration />
			</Grid.Col>
			<Grid.Col {...cols}>
				<DonationAlertsIntegration />
			</Grid.Col>
			<Grid.Col {...cols}>
				<StreamlabsIntegration />
			</Grid.Col>
			<Grid.Col {...cols}>
				<FaceitIntegration />
			</Grid.Col>
			<Grid.Col {...cols}>
				<DonatePayIntegration />
			</Grid.Col>
			<Grid.Col {...cols}>
				<DonatelloIntegration />
			</Grid.Col>
			<Grid.Col {...cols}>
				<DonateStreamIntegration />
			</Grid.Col>
			<Grid.Col {...cols}>
				<ValorantIntegration />
			</Grid.Col>
		</Grid>
	);
}

// frontend/dashboard/src/pages/Integrations.vue
<script setup lang="ts">
import Discord from '@/components/integrations/discord.vue'
import Donatello from '@/components/integrations/donatello.vue'
import Donatepay from '@/components/integrations/donatepay.vue'
import Donatestream from '@/components/integrations/donatestream.vue'
import Donationalerts from '@/components/integrations/donationalerts.vue'
import Faceit from '@/components/integrations/faceit.vue'
import Lastfm from '@/components/integrations/lastfm.vue'
import Spotify from '@/components/integrations/spotify.vue'
import Streamlabs from '@/components/integrations/streamlabs.vue'
import Vk from '@/components/integrations/vk.vue'
import SevenTv from '@/features/integrations/ui/seventv/seven-tv.vue'
import Valorant from '@/features/integrations/ui/valorant/valorant.vue'
import PageLayout from '@/layout/page-layout.vue'
</script>

<template>
	<PageLayout>
		<template #title> Integrations </template>

		<template #content>
			<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
				<SevenTv />
				<Discord />
				<Spotify />
				<Lastfm />
				<Vk />
				<Donationalerts />
				<Streamlabs />
				<Donatello />
				<Donatepay />
				<Donatestream />
				<Faceit />
				<Valorant />
			</div>
		</template>
	</PageLayout>
</template>

<style>
.integrations {
	display: flex;
	align-items: center;
	justify-content: center;
	max-width: 60vw;
	margin: 0 auto;
}

@media screen and (max-width: 1024px) {
	.integrations {
		max-width: 80vw;
	}
}
</style>
