// frontend/dashboard/src/components/integrations/donatello.vue
<script setup lang="ts">
import { NTimeline, NTimelineItem, NText } from 'naive-ui';

import { useDonatelloIntegration } from '@/api/index.js';
import DonatelloSVG from '@/assets/icons/integrations/donatello.svg?component';
import CopyInput from '@/components/copyInput.vue';
import DonateDescription from '@/components/integrations/helpers/donateDescription.vue';
import WithSettings from '@/components/integrations/variants/withSettings.vue';

const { data: donatelloData } = useDonatelloIntegration();

const webhookUrl = `${window.location.origin}/api/webhooks/integrations/donatello`;
</script>

<template>
	<with-settings
		title="Donatello"
		:icon="DonatelloSVG"
		icon-width="80px"
	>
		<template #description>
			<donate-description />
		</template>
		<template #settings>
			<n-timeline>
				<n-timeline-item type="info" title="Step 1">
					<n-text>
						Go to
						<a
							href="https://donatello.to/panel/settings"
							target="_blank"
							class="link"
						>
							https://donatello.to/panel/settings
						</a>
						and scroll to "Вихідний API" section
					</n-text>
				</n-timeline-item>
				<n-timeline-item type="info" title="Step 2">
					<n-text>Copy api key and paste into "Api Key" input</n-text>
					<copy-input :text="donatelloData?.integrationId ?? ''" style="margin-top: 5px" />
				</n-timeline-item>
				<n-timeline-item type="info" title="Step 3">
					<n-text>Copy link and paste into "Link" field</n-text>
					<copy-input :text="webhookUrl" style="margin-top: 5px" />
				</n-timeline-item>
			</n-timeline>
		</template>
	</with-settings>
</template>

<style scoped>
.link {
	color: #41c489;
	text-decoration: none
}
</style>

// frontend/dashboard/components/integrations/donatello.tsx
import { ActionIcon, Alert, Anchor, CopyButton, Stepper, Text, TextInput } from '@mantine/core';
import { showNotification } from '@mantine/notifications';
import { IconCopy, IconDeviceFloppy, IconInfoCircle, IconLink } from '@tabler/icons';
import { useTranslation } from 'next-i18next';
import { Fragment, useEffect, useState } from 'react';

import { ManualComponent } from './manualComponent';

import { useDonatelloIntegration } from '@/services/api/integrations/donatello';

export default () => {
	const manager = useDonatelloIntegration();
	const { data: apiKey } = manager.useData();

	const [key, setKey] = useState<string>();

	const siteUrl = `${window.location.origin}/api/webhooks/integrations/donatello`;

	useEffect(() => {
		if (apiKey) {
			setKey(apiKey);
		}
	}, [apiKey]);


	return (
		<ManualComponent
			integrationKey={'donatello'}
			imageSize={50}
			body={
				<Stepper
					active={0}
					allowNextStepsSelect={false}
					orientation="vertical"
					w={'100%'}
					styles={{
						step: {
							width: '100%',
						},
						stepBody: {
							width: '100%',
						},
					}}
				>
					<Stepper.Step
						label="Step 1"
						description={
							<Fragment>
								Go to{' '}
								<Anchor href={'https://donatello.to/panel/settings'} target={'_blank'}>
									https://donatello.to/panel/settings
								</Anchor>{' '}
								and scroll to "Вихідний API" section
							</Fragment>
						}
					/>
					<Stepper.Step
						label="Step 2"
						description={
							<div>
								Copy api key and paste into "Api Key" input
								<TextInput
									mt={5}
									value={key}
									onChange={() => {}}
									variant={'filled'}
									rightSection={
										<CopyButton value={apiKey!}>
											{({ copy }) => (
												<ActionIcon
													onClick={() => {
														copy();
														showNotification({
															color: 'green',
															title: 'Copied',
															message: 'Copied to clipboard',
														});
													}}
												>
													<IconCopy />
												</ActionIcon>
											)}
										</CopyButton>
									}
								/>
							</div>
						}
					/>
					<Stepper.Step
						label="Step 3"
						description={
							<div>
								Copy link and paste into link field
								<TextInput
									styles={{
										input: {
											width: '100%',
										},
									}}
									mt={5}
									value={siteUrl}
									onChange={() => {}}
									variant={'filled'}
									rightSection={
										<CopyButton value={siteUrl!}>
											{({ copy }) => (
												<ActionIcon
													onClick={() => {
														copy();
														showNotification({
															color: 'green',
															title: 'Copied',
															message: 'Copied to clipboard',
														});
													}}
												>
													<IconCopy />
												</ActionIcon>
											)}
										</CopyButton>
									}
								/>
							</div>
						}
					/>
				</Stepper>
			}
		/>
	);
};
