// frontend/dashboard-new/src/components/integrations/streamlabs.vue
<script setup lang='ts'>
import { useStreamlabsIntegration } from '@/api/index.js';
import IconStreamLabs from '@/assets/icons/integrations/streamlabs.svg?component';
import OauthComponent from '@/components/integrations/oauthComponent.vue';

const manager = useStreamlabsIntegration();
const { data } = manager.useData();
const logout = manager.useLogout();
const getAuthLink = manager.useAuthLink();
</script>

<template>
  <oauth-component name="StreamLabs" :data="data" :logout="logout.mutateAsync" :getLoginLink="getAuthLink.refetch">
    <template #icon>
      <IconStreamLabs style="width: 30px;" />
    </template>
  </oauth-component>
</template>

// frontend/dashboard/components/integrations/streamlabs.tsx
import { OAuthComponent } from './oauthComponent';

import { useStreamlabs } from '@/services/api/integrations';

export const StreamlabsIntegration: React.FC = () => {
  const manager = useStreamlabs();
  const logout = manager.useLogout();
  const { data: profile } = manager.useData();
  const auth = manager.useGetAuthLink();

  async function login() {
    if (auth.data) {
      window.location.replace(auth.data);
    }
  }

  return (
		<OAuthComponent
			integrationKey={'streamlabs'}
			logout={logout.mutate}
			login={login}
			profile={profile ? {
				name: profile?.name,
				avatar: profile?.avatar,
			} : undefined}
		/>
  );
};
