// frontend/dashboard/src/components/integrations/valorant.vue
<script setup lang='ts'>
import { NInput, NFormItem } from 'naive-ui';
import { ref, watch } from 'vue';

import { useValorantIntegration } from '@/api/index.js';
import ValorantSVG from '@/assets/icons/integrations/valorant.svg';
import WithSettings from '@/components/integrations/variants/withSettings.vue';

const manager = useValorantIntegration();
const { data } = manager.useGetData();
const { mutateAsync } = manager.usePost();

const userName = ref<string>('');

watch(data, (value) => {
	if (value?.userName) {
		userName.value = value.userName;
	}
});

async function save() {
	console.log(userName.value);
	await mutateAsync(userName.value);
}
</script>

<template>
	<with-settings name="Valorant" :save="save">
		<template #icon>
			<ValorantSVG style="width: 50px; display: flex" />
		</template>
		<template #settings>
			<n-form-item label="Valorant username with tag">
				<n-input
					v-model:value="userName"
					type="text"
					placeholder="username#tag"
				/>
			</n-form-item>
		</template>
	</with-settings>
</template>

// frontend/dashboard/components/integrations/valorant.tsx
import {
	TextInput,
} from '@mantine/core';
import { useEffect, useState } from 'react';

import { ManualComponent } from './manualComponent';

import { useValorantIntegration } from '@/services/api/integrations/valorant';

export const ValorantIntegration: React.FC = () => {
	const manager = useValorantIntegration();
	const { data } = manager.useData();
	const update = manager.usePost();

	const [username, setUsername] = useState<string>();

	useEffect(() => {
		if (typeof data?.username !== 'undefined') {
			setUsername(data.username);
		}
	}, [data]);

	async function save() {
		if (typeof username == 'undefined') return;
		await update.mutateAsync({ username });
	}

	return (
		<ManualComponent
			integrationKey={'valorant'}
			save={save}
			imageSize={50}
			body={
				<TextInput
					label='Valorant username'
					value={username}
					onChange={(v) => setUsername(v.currentTarget.value)}
					placeholder={'Name#tag'}
				/>
			}
		/>
	);
};
