// apps/dashboard/pages/commands.tsx
import { ActionIcon, Badge, Button, Flex, Switch, Table, Tabs, Text } from '@mantine/core';
import { useViewportSize } from '@mantine/hooks';
import {
  IconClipboardCopy,
  IconPencilPlus,
  IconSword,
  IconUser,
  IconTrash,
  IconPencil,
} from '@tabler/icons';
import type { ChannelCommand, CommandModule } from '@tsuwari/typeorm/entities/ChannelCommand';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useState } from 'react';

import { CommandDrawer } from '../components/commands/drawer';

import { confirmDelete } from '@/components/confirmDelete';
import { useCommandManager } from '@/services/api';

type Module = keyof typeof CommandModule;

export const getServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['commands'])),
  },
});

export default function Commands() {
  const [activeTab, setActiveTab] = useState<Module | null>('CUSTOM');
  const [editDrawerOpened, setEditDrawerOpened] = useState(false);
  const [editableCommand, setEditableCommand] = useState<ChannelCommand | undefined>();
  const viewPort = useViewportSize();
  const { t } = useTranslation('commands');

  const manager = useCommandManager();
  const { data: commands } = manager.getAll();

  return (
    <div>
      <Flex direction="row" justify="space-between">
        <Text size="lg">{t('title')}</Text>
        <Button
          color="green"
          onClick={() => {
            setEditableCommand(undefined);
            setEditDrawerOpened(true);
          }}
        >
          {t('create')}
        </Button>
      </Flex>
      <Tabs onTabChange={(n) => setActiveTab(n as Module)}>
        <Tabs.List>
          <Tabs.Tab value="CUSTOM" icon={<IconPencilPlus size={14} />}>
            {t('tabs.custom')}
          </Tabs.Tab>
          <Tabs.Tab value="CHANNEL" icon={<IconUser size={14} />}>
            {t('tabs.channel')}
          </Tabs.Tab>

          <Tabs.Tab value="MODERATION" icon={<IconSword size={14} />}>
            {t('tabs.moderation')}
          </Tabs.Tab>
          <Tabs.Tab value="MANAGE" icon={<IconClipboardCopy size={14} />}>
            {t('tabs.manage')}
          </Tabs.Tab>
          <Tabs.Tab value="DOTA">{t('tabs.dota')}</Tabs.Tab>
        </Tabs.List>
      </Tabs>
      <Table>
        <thead>
          <tr>
            <th>Name</th>
            {viewPort.width > 550 && (
              <>
                <th>Responses</th>
                <th>Status</th>
              </>
            )}
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          {commands &&
            commands.length &&
            commands
              .filter((c) => c.module === activeTab)
              .map((command) => (
                <tr key={command.id}>
                  <td>
                    <Badge>{command.name}</Badge>
                  </td>
                  {viewPort.width > 550 && (
                    <>
                      <td>
                        {command.module != 'CUSTOM' && <Badge>This is built-in command</Badge>}
                        {command.module === 'CUSTOM' &&
                          (command.responses?.map((r, i) => (
                            <p key={i} style={{ margin: 0 }}>
                              {r.text}
                            </p>
                          )) || <Badge>No Response</Badge>)}
                      </td>
                      <td>
                        <Switch
                          checked={command.enabled}
                          onChange={(event) => {
                            manager.patch(command.id, { enabled: event.currentTarget.checked });
                          }}
                        />
                      </td>
                    </>
                  )}
                  <td>
                    <Flex direction="row" gap="xs">
                      <ActionIcon
                        onClick={() => {
                          setEditableCommand(commands.find((c) => c.id === command.id)!);
                          setEditDrawerOpened(true);
                        }}
                        variant="filled"
                        color="blue"
                      >
                        <IconPencil size={14} />
                      </ActionIcon>
                      {command.module === 'CUSTOM' && (
                        <ActionIcon
                          onClick={() =>
                            confirmDelete({
                              onConfirm: () => manager.delete(command.id),
                            })
                          }
                          variant="filled"
                          color="red"
                        >
                          <IconTrash size={14} />
                        </ActionIcon>
                      )}
                    </Flex>
                  </td>
                </tr>
              ))}
        </tbody>
      </Table>

      <CommandDrawer
        opened={editDrawerOpened}
        setOpened={setEditDrawerOpened}
        command={editableCommand}
      />
    </div>
  );
}

// apps/frontend/src/pages/Commands.vue
<script lang="ts" setup>
import { mdiPencil, mdiTrashCan } from '@mdi/js';
import { ChannelCommand, type CommandModule } from '@tsuwari/typeorm/entities/ChannelCommand';
import { computed, ref } from 'vue';
import { useDisplay } from 'vuetify/lib/framework.mjs';

import confirmDeletion from '@/components/confirmDeletion.vue';
import CommandDrawer from '@/components/drawers/commandEdit.vue';
import { commands } from '@/data/commands';
import { tabs } from '@/data/commandsTabs';

const selectedTab = ref<keyof typeof CommandModule>('CUSTOM');

const { smAndDown } = useDisplay();

const commandsList = computed(() => {
  return commands.value.filter(c => c.module === selectedTab.value);
});

const isCommandEdit = ref(false);
const editableCommand = ref<ChannelCommand | undefined>();

function setEditCommand(c: ChannelCommand) {
  isCommandEdit.value = true;
  editableCommand.value = c;
}

const symbolsRegexp = /^\W$|_|/;
function preventSymbolsInCommandName(e: KeyboardEvent) {
  // if (symbolsRegexp.test(e.key)) {
  //   e.preventDefault();
  // }
}

const c = console;

function cancelEdit() {
  isCommandEdit.value = false;
  editableCommand.value = undefined;
}

function deleteCommand(id: string) {
  return null;
}
</script>

<template>
  <div class="d-flex flex-column">
    <div>
      <v-tabs
        v-model="selectedTab"
        centered
        stacked
        fixed-tabs
        class="d-flex justify-center"
      >
        <v-tab v-for="tab of tabs" :key="tab.value" :value="tab.value">
          <v-icon v-if="tab.icon">
            {{ tab.icon }}
          </v-icon>
          {{ tab.name }}
        </v-tab>
      </v-tabs>
    </div>
    

    <v-table class="mt-2">
      <thead>
        <tr>
          <th class="text-left">
            Name
          </th>
          <th v-if="!smAndDown && selectedTab === 'CUSTOM'" class="text-left">
            Responses
          </th>
          <th class="text-left">
            Status
          </th>
          <th class="text-left">
            Actions
          </th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="command in commandsList"
          :key="command.name"
        >
          <td :width="(!smAndDown && selectedTab === 'CUSTOM') ? '10%' : '100%'">
            {{ command.name }}
          </td>
          <td v-if="!smAndDown && selectedTab === 'CUSTOM'">
            <p v-if="command.responses!.length > 1" v-html="command.responses?.map((t) => t.text).join('<br>')"></p>
            <p v-else>
              {{ command.responses![0]?.text ?? '' }}
            </p>
          </td>
          <td>
            <v-switch v-model="command.enabled" class="d-flex justify-center" color="green"></v-switch>
          </td>
          <td>
            <div class="d-flex flex-row">
              <v-btn :icon="mdiPencil" size="x-small" color="purple" @click="setEditCommand(command)" />
              <confirmDeletion @on-confirmed="() => deleteCommand(command.id)">
                <v-btn :icon="mdiTrashCan" size="x-small" color="red" class="ml-2" @click="$emit('click')" />
              </confirmDeletion>
            </div>
          </td>
        </tr>
      </tbody>
    </v-table>


    <v-navigation-drawer
      v-if="isCommandEdit"
      v-model="isCommandEdit"
      temporary
      location="right"
      :class="[smAndDown ? 'w-100' : 'w-50']"
    >
      <CommandDrawer :command="editableCommand!" @cancel="cancelEdit" />
    </v-navigation-drawer>
  </div>
</template>
