// apps/dashboard/pages/moderation.tsx
import { Grid } from '@mantine/core';
import {
  IconLambda,
  IconLetterCaseUpper,
  IconLink,
  IconMoodSmile,
  IconPlaylistX,
  IconTextWrapDisabled,
} from '@tabler/icons';

import { ModerationCard } from '../components/moderation/card';

export default function () {
  return (
    <Grid justify="center">
      <Grid.Col xs={12} sm={12} md={5} lg={5} xl={5}>
        <ModerationCard title="Links" icon={IconLink} iconColor="cyan">
          123
        </ModerationCard>
      </Grid.Col>
      <Grid.Col xs={12} sm={12} md={5} lg={5} xl={5}>
        <ModerationCard title="Caps" icon={IconLetterCaseUpper} iconColor="orange">
          Caps
        </ModerationCard>
      </Grid.Col>
      <Grid.Col xs={12} sm={12} md={5} lg={5} xl={5}>
        <ModerationCard title="Emotes" icon={IconMoodSmile} iconColor="yellow">
          123
        </ModerationCard>
      </Grid.Col>
      <Grid.Col xs={12} sm={12} md={5} lg={5} xl={5}>
        <ModerationCard title="LongMessage" icon={IconTextWrapDisabled}>
          123
        </ModerationCard>
      </Grid.Col>
      <Grid.Col xs={12} sm={12} md={5} lg={5} xl={5} color="red">
        <ModerationCard title="Blacklists" icon={IconPlaylistX}>
          123
        </ModerationCard>
      </Grid.Col>
      <Grid.Col xs={12} sm={12} md={5} lg={5} xl={5}>
        <ModerationCard title="Symbols" icon={IconLambda} iconColor="green">
          123
        </ModerationCard>
      </Grid.Col>
    </Grid>
  );
}

// apps/frontend/src/pages/Moderation.vue
<script lang="ts" setup>
import { mdiLinkBoxVariant, mdiCapsLock, mdiClipboard, mdiCalculatorVariant, mdiEmoticon, mdiWrapDisabled } from '@mdi/js';
import { useDisplay } from 'vuetify';

import Card from '@/components/moderation/card.vue';

const { smAndDown } = useDisplay();
</script>

<template>
  <div>
    <v-row justify="center">
      <v-col :cols="smAndDown ? 12 : 4">
        <Card type="links" :icon="mdiLinkBoxVariant" icon-color="blue" />
      </v-col>
      <v-col :cols="smAndDown ? 12 : 4">
        <Card type="caps" :icon="mdiCapsLock" icon-color="orange" />
      </v-col>
    </v-row>
    <v-row justify="center">
      <v-col :cols="smAndDown ? 12 : 4">
        <Card type="symbols" :icon="mdiCalculatorVariant" icon-color="green" />
      </v-col>

      <v-col :cols="smAndDown ? 12 : 4">
        <Card type="emotes" :icon="mdiEmoticon" icon-color="yellow" />
      </v-col>
    </v-row>
    <v-row justify="center">
      <v-col :cols="smAndDown ? 12 : 4">
        <Card type="blacklists" :icon="mdiClipboard" icon-color="red" />
      </v-col>
      <v-col :cols="smAndDown ? 12 : 4">
        <Card type="longMessage" :icon="mdiWrapDisabled" icon-color="cyan" />
      </v-col>
    </v-row>
  </div>
</template>
