// apps/dashboard/pages/settings.tsx
import { Grid } from '@mantine/core';

import { DashboardAccess } from '../components/settings.tsx/dashboardAccess';

export default function Settings() {
  return (
    <Grid grow>
      <Grid.Col span={4}>
        <DashboardAccess />
      </Grid.Col>
      <Grid.Col span={4}></Grid.Col>
      <Grid.Col span={4}></Grid.Col>
    </Grid>
  );
}

// apps/frontend/src/pages/Settings.vue
<script lang="ts" setup>
import { useDisplay } from 'vuetify';

import DashboardAccess from '@/components/settings/dashboardAccess.vue';

const { smAndDown } = useDisplay();
</script>

<template>
  <div>
    <v-row>
      <v-col :cols="smAndDown ? 12 : 3">
        <DashboardAccess />
      </v-col>
    </v-row>
  </div>
</template>
