// apps/dashboard/pages/timers.tsx
import { ActionIcon, Badge, Button, Flex, Switch, Table, Text } from '@mantine/core';
import { useViewportSize } from '@mantine/hooks';
import { IconPencil, IconTrash } from '@tabler/icons';
import { ChannelTimer } from '@tsuwari/typeorm/entities/ChannelTimer';
import { useState } from 'react';

import { TimerDrawer } from '../components/timers/drawer';

import { confirmDelete } from '@/components/confirmDelete';
import { useTimersManager } from '@/services/api';

export default function () {
  const [editDrawerOpened, setEditDrawerOpened] = useState(false);
  const [editableTimer, setEditableTimer] = useState<ChannelTimer | undefined>();
  const viewPort = useViewportSize();

  const manager = useTimersManager();
  const { data: timers } = manager.getAll();

  return (
    <div>
      <Flex direction="row" justify="space-between">
        <Text size="lg">Timers</Text>
        <Button
          color="green"
          onClick={() => {
            setEditableTimer(undefined);
            setEditDrawerOpened(true);
          }}
        >
          Create
        </Button>
      </Flex>
      <Table>
        <thead>
          <tr>
            <th>Name</th>
            {viewPort.width > 550 && <th>Responses</th>}
            <th>Time Interval</th>
            <th>Messages Interval</th>
            {viewPort.width > 550 && <th>Status</th>}
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {timers &&
            timers.map((timer, idx) => (
              <tr key={timer.id}>
                <td>
                  <Badge>{timer.name}</Badge>
                </td>
                {viewPort.width > 550 && (
                  <td>
                    {timer.responses.map((r, i) => (
                      <p key={i} style={{ margin: 0 }}>
                        {r.text}
                      </p>
                    ))}
                  </td>
                )}

                <td>{timer.timeInterval} seconds</td>
                <td>{timer.messageInterval}</td>
                {viewPort.width > 550 && (
                  <td>
                    <Switch
                      checked={timer.enabled}
                      onChange={(event) => (timer.enabled = event.currentTarget.checked)}
                    />
                  </td>
                )}
                <td>
                  <Flex direction="row" gap="xs">
                    <ActionIcon
                      onClick={() => {
                        setEditableTimer(timers[idx] as any);
                        setEditDrawerOpened(true);
                      }}
                      variant="filled"
                      color="blue"
                    >
                      <IconPencil size={14} />
                    </ActionIcon>

                    <ActionIcon
                      onClick={() =>
                        confirmDelete({
                          onConfirm: () => manager.delete(timer.id),
                        })
                      }
                      variant="filled"
                      color="red"
                    >
                      <IconTrash size={14} />
                    </ActionIcon>
                  </Flex>
                </td>
              </tr>
            ))}
        </tbody>
      </Table>

      <TimerDrawer
        opened={editDrawerOpened}
        setOpened={setEditDrawerOpened}
        timer={editableTimer}
      />
    </div>
  );
}

// apps/frontend/src/pages/Timers.vue
<script lang="ts" setup>
import { mdiPencil, mdiTrashCan } from '@mdi/js';
import { ChannelTimer } from '@tsuwari/typeorm/entities/ChannelTimer';
import { computed, ref } from 'vue';
import { useDisplay } from 'vuetify/lib/framework.mjs';

import TimersDrawer from '@/components/drawers/timerEdit.vue';
import { timers } from '@/data/timers';

const display = useDisplay();
const isMobile = computed(() => {
  return display.xs.value || display.sm.value;
});

const isTimerEdit = ref(false);
const editableTimer = ref<ChannelTimer | undefined>();

function setEditTimer(c: ChannelTimer) {
  isTimerEdit.value = true;
  editableTimer.value = c;
}

function cancelEdit() {
  isTimerEdit.value = false;
  editableTimer.value = undefined;
}
</script>

<template>
  <div class="d-flex flex-column">
    <v-table class="mt-2">
      <thead>
        <tr>
          <th class="text-left">
            Name
          </th>
          <th class="text-left">
            Responses
          </th>
          <th class="text-left">
            Status
          </th>
          <th class="text-left">
            Actions
          </th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="timer in timers"
          :key="timer.name"
        >
          <td>
            {{ timer.name }}
          </td>
          <td v-if="!isMobile">
            <div v-if="timer.responses?.length > 1">
              <p 
                v-for="(r, i) of timer.responses"
               
                :key="i"
              >
                {{ r.text }}
                <br />
              </p>
            </div>
            
            <p v-else>
              {{ timer.responses[0]!.text ?? '' }}
            </p>
          </td>
          <td>
            <v-switch v-model="timer.enabled" class="d-flex justify-center" color="green"></v-switch>
          </td>
          <td>
            <div class="d-flex flex-row">
              <v-btn :icon="mdiPencil" size="x-small" color="purple" @click="setEditTimer(timer)" />
              <confirmDeletion @on-confirmed="() => {}">
                <v-btn :icon="mdiTrashCan" size="x-small" color="red" class="ml-2" @click="$emit('click')" />
              </confirmDeletion>
            </div>
          </td>
        </tr>
      </tbody>
    </v-table>


    <v-navigation-drawer
      v-if="isTimerEdit"
      v-model="isTimerEdit"
      temporary
      location="right"
      :class="[isMobile ? 'w-100' : 'w-50']"
    >
      <TimersDrawer :timer="editableTimer!" @cancel="cancelEdit" />
    </v-navigation-drawer>
  </div>
</template>
