// apps/dashboard/pages/variables.tsx
import { Badge, Button, Table } from '@mantine/core';
import { useLocalStorage } from '@mantine/hooks';
import { Dashboard } from '@tsuwari/shared';
import { ChannelCustomvar } from '@tsuwari/typeorm/entities/ChannelCustomvar';
import { useState } from 'react';
import useSWR from 'swr';

import { VariableDrawer } from '../components/variables/drawer';
import { swrFetcher } from '../services/swrFetcher';

export default function () {
  const [editDrawerOpened, setEditDrawerOpened] = useState(false);
  const [editableVariable, setEditableVariable] = useState<ChannelCustomvar>({} as any);
  const [selectedDashboard] = useLocalStorage<Dashboard>({
    key: 'selectedDashboard',
    serialize: (v) => JSON.stringify(v),
    deserialize: (v) => JSON.parse(v),
  });

  const { data: variables } = useSWR<ChannelCustomvar[]>(
    selectedDashboard ? `/api/v1/channels/${selectedDashboard.channelId}/variables` : null,
    swrFetcher,
  );

  return (
    <div>
      <Table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {variables &&
            variables.map((element, idx) => (
              <tr key={element.id}>
                <td>
                  <Badge>{element.name}</Badge>
                </td>
                <td>
                  <Badge color="cyan">{element.type}</Badge>
                </td>
                <td>
                  <Button
                    onClick={() => {
                      setEditableVariable(variables[idx] as any);
                      setEditDrawerOpened(true);
                    }}
                  >
                    Edit
                  </Button>
                </td>
              </tr>
            ))}
        </tbody>
      </Table>

      <VariableDrawer
        opened={editDrawerOpened}
        setOpened={setEditDrawerOpened}
        variable={editableVariable}
      />
    </div>
  );
}

// apps/frontend/src/pages/Variables.vue
<script lang="ts" setup>
import { mdiPencil, mdiTrashCan } from '@mdi/js';
import { type ChannelCustomvar } from '@tsuwari/typeorm/entities/ChannelCustomvar';
import { ref } from 'vue';
import { useDisplay } from 'vuetify';

import confirmDeletion from '@/components/confirmDeletion.vue';
import VariableDrawer from '@/components/drawers/variableEdit.vue';
import { variables } from '@/data/variables';

const { mobile } = useDisplay();
const isVariableEdit = ref(false);
const editableVariable = ref<ChannelCustomvar | undefined>();

function setEditKeyword(c: ChannelCustomvar) {
  isVariableEdit.value = true;
  editableVariable.value = JSON.parse(JSON.stringify(c));
}

function cancelEdit() {
  isVariableEdit.value = false;
  editableVariable.value = undefined;
}

function deleteVariable(v: ChannelCustomvar) {}

function onDelete(v: ChannelCustomvar) {
  console.log(v);
}
</script>

<template>
  <div class="d-flex flex-column">
    <v-table class="mt-2">
      <thead>
        <tr>
          <th class="text-left">
            Name
          </th>
          <th class="text-left">
            Response
          </th>
          <th class="text-left">
            Type
          </th>
          <th class="text-left">
            Response
          </th>
          <th class="text-left">
            Actions
          </th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="variable in variables"
          :key="variable.id"
        >
          <td>{{ variable.name }}</td>
          <td>{{ variable.response }}</td>
          <td>
            <v-chip size="small">
              {{ variable.type }}
            </v-chip>
          </td>
          <td>
            <p v-if="variable.type === 'TEXT'">
              {{ variable.response }}
            </p>
          </td>
          <td>
            <div class="d-flex flex-row">
              <v-btn :icon="mdiPencil" size="x-small" color="purple" @click="setEditKeyword(variable)" />
              <confirmDeletion :cb="() => deleteVariable(variable)">
                <v-btn :icon="mdiTrashCan" size="x-small" color="red" class="ml-2" @click="$emit('click')" />
              </confirmDeletion>
            </div>
          </td>
        </tr>
      </tbody>
    </v-table>


    <v-navigation-drawer
      v-if="isVariableEdit"
      v-model="isVariableEdit"
      temporary
      location="right"
      :class="[mobile ? 'w-100' : 'w-50']"
    >
      <VariableDrawer :variable="editableVariable!" @cancel="cancelEdit" />
    </v-navigation-drawer>
  </div>
</template>
