// frontend/landing/src/components/login.vue
<script lang="ts" setup>
import { onMounted } from 'vue';

import { browserUnProtectedClient } from '../api/twirp-browser.js';

const url = new URL(window.location.href);
const code = url.searchParams.get('code');
const err = url.searchParams.get('error');

onMounted(async () => {
	if (!code) return window.location.replace('/');

	await browserUnProtectedClient.authPostCode({
		code,
	});
	window.location.replace('/dashboard');
});
</script>

// frontend/landing/src/components/login.tsx
import { useEffect, useState } from 'preact/compat';

import { browserUnProtectedClient } from '../api/twirp-browser.js';

export default () => {
	const [error, setError] = useState('');

	useEffect(() => {
		const url = new URL(window.location.href);
		const code = url.searchParams.get('code');
		const err = url.searchParams.get('error');
		if (err) {
			setError(err);
		} else {
			browserUnProtectedClient.authPostCode({
				code,
			})
				.then(() => window.location.replace('/dashboard'))
				.catch(() => setError('internal error'));
		}
	}, []);

	return <>
	Login
	{error}
</>;
};
