// frontend/landing/src/components/profile.tsx
import { type Profile } from '@twir/grpc/generated/api/api/auth';
import { useState, Fragment, useEffect } from 'preact/compat';

import { browserProtectedClient, browserUnProtectedClient } from '../api/twirp-browser.js';
import TwitchIcon from '../assets/login-twitch.svg';

export default () => {
	const [profile, setProfile] = useState<Profile | null>(null);
	const [authLink, setAuthLink] = useState<string | null>(null);

	const [isLoading, setIsLoading] = useState(true);

	useEffect(() => {
		browserUnProtectedClient.authGetLink({
			state: window.btoa(window.location.origin),
		})
			.then((r) => setAuthLink(r.response.link));

		browserProtectedClient.authUserProfile({})
			.then((r) => setProfile(r.response))
			.finally(() => setIsLoading(false));
	}, []);

	return <a
		class="flex px-[18px] py-[10px] items-center gap-[8px] bg-[#5D58F5] text-white rounded-lg"
		href={profile ? '/dashboard' : authLink}
	>
		{isLoading && <Fragment>
			<svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
				<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
				<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
			</svg>
			Loading...
		</Fragment>}

		{!isLoading && !profile && <Fragment>
			<span class="font-['Inter'] font-semibold text-white text-base">Login</span>
			<img src={TwitchIcon} width="18" height="19"/>
		</Fragment>}

		{!isLoading && profile &&
		<Fragment>
			<img src={profile.avatar} class="rounded-full" width="30" height="30"/>
			{profile.displayName}
		</Fragment>}
	</a>;
};

// frontend/landing/src/components/Profile.vue
<script lang="ts" setup>
import { Profile } from '@twir/grpc/generated/api/api/auth';
import { computed, ref } from 'vue';

import { browserProtectedClient, browserUnProtectedClient } from '../api/twirp-browser.js';
import ErrorIcon from '../icons/Error.svg?component';
import Loader from '../icons/Loader.svg?component';
import TwitchIcon from '../icons/TwitchLogo.svg?component';

const profile = ref<Profile | null>(null);
const authLink = ref<string | null>(null);

const isLoading = computed(
	() => authLink.value === null && profile.value === null && isError.value === false,
);
const isError = ref(false);
const error = ref<string | null>(null);

browserUnProtectedClient
	.authGetLink({
		state: window.btoa(window.location.origin),
	})
	.then((r) => (authLink.value = r.response.link))
	.catch((err) => {
		isError.value = true;
		console.error(err);
		error.value = String(err);
	});

browserProtectedClient
	.authUserProfile({})
	.then((r) => (profile.value = r.response))
	.catch((err) => {
		isError.value = true;
		console.error(err);
		error.value = String(err);
	});
</script>

<template>
	<Loader v-if="isLoading" class="w-6 h-6 animate-spin stroke-white/75 stroke-[1.5] m-2" />
	<span v-else-if="isError" class="text-[#FD6675] inline-flex items-center gap-x-2 max-w-sm">
		<ErrorIcon class="fill-[#FD6675] h-5 w-5 flex-shrink-0 items-center" />
		<span class="line-clamp-1">{{ error }}</span>
	</span>
	<a v-else-if="profile" href="/dashboard" class="text-white/75 inline-flex gap-x-3 items-center">
		{{ profile.displayName }}
		<img :src="profile.avatar" class="rounded-full w-9 h-9 object-cover" />
	</a>
	<a
		v-else
		class="flex flex-row px-4 py-2 items-center gap-2 bg-[#5D58F5] text-white rounded-lg font-medium cursor-pointer hover:bg-[#6964FF]"
		:href="authLink">
		Login
		<TwitchIcon class="w-5 h-5 fill-white" />
	</a>
</template>
