// frontend/overlays/src/pages/obs.tsx
import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import useWebSocket from 'react-use-websocket';

import { useObs } from '../hooks/obs';

export const OBS: React.FC = () => {
  const { apiKey } = useParams();
  const obs = useObs();

  const [settings, setSettings] = useState<Record<string, any>>({});

  const [url, setUrl] = useState<string | null>(null);
  useEffect(() => {
    if (!apiKey) return;

    const urlPrefix = window.location.protocol === 'https:' ? 'wss' : 'ws';
    setUrl(`${urlPrefix}://${window.location.host}/socket/obs?apiKey=${apiKey}`);
  }, [apiKey]);

  const { lastMessage, sendMessage } = useWebSocket(url, {
    shouldReconnect: () => true,
    onOpen: () => console.log('Twir socket opened'),
    reconnectInterval: 500,
  });

  useEffect(() => {
    if (!lastMessage) return;
    const { eventName, data } = JSON.parse(lastMessage.data);

    if (eventName === 'connected') {
      sendMessage(JSON.stringify({ eventName: 'requestSettings' }));
    }

    switch (eventName) {
      case 'settings': setSettings(data); break;
      case 'setScene': obs.setScene(data.sceneName); break;
      case 'toggleSource': obs.toggleSource(data.sourceName); break;
      case 'toggleAudioSource': obs.toggleAudioSource(data.audioSourceName); break;
      case 'setVolume': obs.setVolume(data.audioSourceName, data.volume); break;
      case 'increaseVolume': obs.changeVolume(data.audioSourceName, data.step, 'increase'); break;
      case 'decreaseVolume': obs.changeVolume(data.audioSourceName, data.step, 'decrease'); break;
      case 'enableAudio': obs.toggleAudioSource(data.audioSourceName, true); break;
      case 'disableAudio': obs.toggleAudioSource(data.audioSourceName, false); break;
      case 'startStart': obs.startStream(); break;
      case 'stopStream': obs.stopStream(); break;
    }
  }, [lastMessage]);

  useEffect(() => {
    if (!settings || !Object.keys(settings).length) {
      obs.disconnect();
      return;
    }

    obs.connect(settings.serverAddress, settings.serverPort, settings.serverPassword).then(() => {
      console.log('Twir obs socket opened');
      sendMessage(JSON.stringify({ eventName: 'obsConnected' }));

      obs.getSources().then((sources) => {
        if (!sources) return;
        sendMessage(JSON.stringify({
          eventName: 'setSources',
          data: sources,
        }));
      });

      obs.getAudioSources().then((sources) => {
        if (!sources) return;
        sendMessage(JSON.stringify({
          eventName: 'setAudioSources',
          data: sources,
        }));
      });

      const scenesHandler = async () => {
        const sources = await obs.getSources();
        sendMessage(JSON.stringify({
          eventName: 'setSources',
          data: sources,
        }));
      };

      const audioHandler = async () => {
        const sources = await obs.getAudioSources();
        sendMessage(JSON.stringify({
          eventName: 'setAudioSources',
          data: sources,
        }));
      };

      obs.instance.current
        .on('SceneListChanged', scenesHandler)

        .on('InputCreated', audioHandler)
        .on('InputRemoved', audioHandler)
        .on('InputNameChanged', audioHandler)

        .on('SceneItemCreated', scenesHandler)
        .on('SceneItemRemoved', scenesHandler);
    });

    return () => {
      obs.disconnect();
    };
  }, [settings]);

  return <div></div>;
};

// web/layers/overlays/pages/o/[apiKey]/obs.vue
<script lang="ts" setup>
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'

import { useObs } from '~/layers/overlays/composables/obs/use-obs.ts'
import {
	type ObsCommand,
	type ObsSettings,
	useObsOverlayGraphQL,
} from '~/layers/overlays/composables/obs/use-obs-graphql.ts'
import { ObsWebsocketCommandAction } from '~~/app/gql/graphql.ts'

definePageMeta({ layout: false })

const route = useRoute()
const obs = useObs()

const apiKey = route.params.apiKey as string
const settings = ref<ObsSettings | null>(null)
const isObsConnected = ref(false)

const { connect, destroy, updateSources, startHeartbeat, stopHeartbeat } = useObsOverlayGraphQL({
	onSettings: async (newSettings) => {
		settings.value = newSettings
		await handleSettingsChange(newSettings)
	},
	onCommand: (command) => {
		handleCommand(command)
	},
})

function handleCommand(command: ObsCommand) {
	switch (command.action) {
		case ObsWebsocketCommandAction.SetScene:
			obs.setScene(command.target)
			break
		case ObsWebsocketCommandAction.ToggleSource:
			obs.toggleSource(command.target)
			break
		case ObsWebsocketCommandAction.ToggleAudio:
			obs.toggleAudioSource(command.target)
			break
		case ObsWebsocketCommandAction.SetVolume:
			if (command.volumeValue !== null && command.volumeValue !== undefined) {
				obs.setVolume(command.target, command.volumeValue)
			}
			break
		case ObsWebsocketCommandAction.IncreaseVolume:
			if (command.volumeStep !== null && command.volumeStep !== undefined) {
				obs.changeVolume(command.target, command.volumeStep, 'increase')
			}
			break
		case ObsWebsocketCommandAction.DecreaseVolume:
			if (command.volumeStep !== null && command.volumeStep !== undefined) {
				obs.changeVolume(command.target, command.volumeStep, 'decrease')
			}
			break
		case ObsWebsocketCommandAction.EnableAudio:
			obs.toggleAudioSource(command.target, true)
			break
		case ObsWebsocketCommandAction.DisableAudio:
			obs.toggleAudioSource(command.target, false)
			break
		case ObsWebsocketCommandAction.StartStream:
			obs.startStream()
			break
		case ObsWebsocketCommandAction.StopStream:
			obs.stopStream()
			break
	}
}

async function handleSettingsChange(newSettings: ObsSettings) {
	if (!newSettings.serverAddress || !newSettings.serverPort || !newSettings.serverPassword) {
		// Stop heartbeat and disconnect if settings are invalid
		stopHeartbeat()
		isObsConnected.value = false
		await obs.disconnect()
		return
	}

	try {
		await obs.connect(newSettings.serverAddress, newSettings.serverPort, newSettings.serverPassword)
		console.log('Twir OBS WebSocket connected')
		isObsConnected.value = true

		// Start heartbeat only after successful OBS connection
		startHeartbeat()

		// Send initial data after connect
		await sendObsData()

		// Setup listeners for OBS changes
		setupObsListeners()
	} catch (error) {
		console.error('Failed to connect to OBS:', error)
		isObsConnected.value = false
		stopHeartbeat()
	}
}

async function sendObsData() {
	const [sources, audioSources] = await Promise.all([obs.getSources(), obs.getAudioSources()])

	if (!sources) return

	// Extract scene names from sources object keys
	const scenes = Object.keys(sources)
	// Flatten all sources from all scenes
	const allSources = Object.values(sources)
		.flat()
		.map((s) => s.name)

	await updateSources({
		scenes,
		sources: allSources,
		audioSources: audioSources ?? [],
	})
}

function setupObsListeners() {
	const updateHandler = async () => {
		await sendObsData()
	}

	// Handle OBS disconnect
	obs.instance.value.on('ConnectionClosed', () => {
		console.log('OBS WebSocket disconnected')
		isObsConnected.value = false
		stopHeartbeat()
	})

	obs.instance.value
		.on('SceneListChanged', updateHandler)
		.on('InputCreated', updateHandler)
		.on('InputRemoved', updateHandler)
		.on('InputNameChanged', updateHandler)
		.on('SceneItemCreated', updateHandler)
		.on('SceneItemRemoved', updateHandler)
}

onMounted(() => {
	connect(apiKey)
})

onBeforeUnmount(() => {
	destroy()
})
</script>

<template>
	<!-- OBS overlay has no visible UI, it only controls OBS -->
</template>
