// frontend/dashboard/components/integrations/donationalerts.tsx
import { OAuthComponent } from './oauthComponent';

import { useDonationAlerts } from '@/services/api/integrations';

export const DonationAlertsIntegration: React.FC = () => {
	const manager = useDonationAlerts();
	const logout = manager.useLogout();
	const { data: profile } = manager.useData();
	const auth = manager.useGetAuthLink();

	async function login() {
		if (auth.data) {
			window.location.replace(auth.data);
		}
	}

	return (
		<OAuthComponent
			integrationKey={'donationalerts'}
			logout={logout.mutate}
			login={login}
			profile={profile ? {
				name: profile?.name,
				avatar: profile?.avatar,
			} : undefined}
		/>
	);
};

// frontend/dashboard/src/components/integrations/donationalerts.vue
<script setup lang='ts'>
import { useDonationAlertsIntegration } from '@/api/index.js';
import IconDonationAlerts from '@/assets/icons/integrations/donationalerts.svg?component';
import OauthComponent from '@/components/integrations/variants/oauth.vue';

const manager = useDonationAlertsIntegration();
const { data } = manager.useData();
const logout = manager.useLogout();
const getAuthLink = manager.useAuthLink();
</script>

<template>
  <oauth-component
    name="DonationAlerts"
    :data="data"
    :logout="logout.mutateAsync"
    :getLoginLink="getAuthLink.refetch"
    :icon="IconDonationAlerts"
  />
</template>
