// frontend/dashboard/components/integrations/faceit.tsx
import { OAuthComponent } from './oauthComponent';

import { useFaceit } from '@/services/api/integrations';

export const FaceitIntegration: React.FC = () => {
	const manager = useFaceit();
	const { data: profile } = manager.useData();
	const auth = manager.useGetAuthLink();
	const logout = manager.useLogout();

	async function login() {
		if (auth.data) {
			window.location.replace(auth.data);
		}
	}

	return (
		<OAuthComponent
			integrationKey={'faceit'}
			logout={logout.mutate}
			login={login}
			profile={profile ? {
				name: profile?.name,
				avatar: profile?.avatar,
			} : undefined}
		/>
	);
};

// frontend/dashboard/src/components/integrations/faceit.vue
<script setup lang='ts'>
import { useFaceitIntegration } from '@/api/index.js';
import IconFaceit from '@/assets/icons/integrations/faceit.svg?component';
import OauthComponent from '@/components/integrations/variants/oauth.vue';

const manager = useFaceitIntegration();
const { data } = manager.useData();
const logout = manager.useLogout();
const { data: authLink } = manager.useAuthLink();
</script>

<template>
	<oauth-component
		name="Faceit"
		:data="data"
		:logout="() => logout.mutateAsync({})"
		:authLink="authLink?.link"
		:icon="IconFaceit"
	/>
</template>
