// frontend/dashboard/components/integrations/lastfm.tsx
import { OAuthComponent } from './oauthComponent';

import { useLastfm } from '@/services/api/integrations';

export const LastfmIntegration: React.FC = () => {
	const manager = useLastfm();
	const { data: profile } = manager.useData();
	const logout = manager.useLogout();
	const auth = manager.useGetAuthLink();

	async function login() {
		if (auth.data) {
			window.location.replace(auth.data);
		}
	}

	return (
		<OAuthComponent
			integrationKey={'lastfm'}
			logout={logout.mutate}
			login={login}
			profile={profile ? {
				name: profile?.name,
				avatar: profile?.image,
			} : undefined}
		/>
	);
};

// frontend/dashboard/src/components/integrations/lastfm.vue
<script setup lang='ts'>
import { useLastfmIntegration } from '@/api/index.js';
import IconLastFM from '@/assets/icons/integrations/lastfm.svg?component';
import OauthComponent from '@/components/integrations/variants/oauth.vue';

const manager = useLastfmIntegration();
const { data } = manager.useData();
const logout = manager.useLogout();
const { data: authLink } = manager.useAuthLink();
</script>

<template>
	<oauth-component
		name="Last.fm"
		:data="data"
		:logout="() => logout.mutateAsync({})"
		:authLink="authLink?.link"
		:icon="IconLastFM"
	/>
</template>
