// frontend/dashboard-new/src/layout/sidebar.vue
<script setup lang="ts">
import {
	IconActivity,
	IconBox,
	IconCalendarEvent,
	IconClipboardCopy,
	IconClockHour7,
	IconCommand,
	IconDashboard,
	IconDeviceDesktop,
	IconDeviceDesktopAnalytics,
	IconHeadphones,
	IconKey,
	IconPencilPlus,
	IconPlayerPlay,
	IconPlaylist,
	IconSettings,
	IconShieldHalfFilled,
	IconSpeakerphone,
	IconSword,
	IconUsers,
} from '@tabler/icons-vue';
import { NMenu, MenuOption, MenuDividerOption } from 'naive-ui';
import { h, ref, onMounted } from 'vue';
import { RouterLink, useRouter } from 'vue-router';

import { renderIcon } from '../helpers/index.js';

const activeKey = ref<string | null>('/');
const menuOptions: (MenuOption | MenuDividerOption)[] = [
	{
		label: 'Dashboard',
		icon: renderIcon(IconDashboard),
		path: '/dashboard',
	},
	{
		label: 'Integrations',
		icon: renderIcon(IconBox),
		path: '/dashboard/integrations',
	},
	{
		label: 'Events',
		icon: renderIcon(IconCalendarEvent),
		path: '/dashboard/events',
	},
	{
		label: 'Overlays',
		icon: renderIcon(IconDeviceDesktop),
		path: '/dashboard/overlays',
	},
	{
		label: 'Song Requests',
		icon: renderIcon(IconHeadphones),
		children: [
			{
				label: 'Player',
				icon: renderIcon(IconPlayerPlay),
				path: '/dashboard/song-requests/player',
			},
			{
				label: 'Settings',
				icon: renderIcon(IconSettings),
				path: '/dashboard/song-requests/settings',
			},
		],
	},
	{
		label: 'Commands',
		icon: renderIcon(IconCommand),
		children: [
			{ label: 'Custom', icon: renderIcon(IconPencilPlus), path: '/dashboard/commands/custom' },
			{ label: 'Stats', icon: renderIcon(IconDeviceDesktopAnalytics), path: '/dashboard/commands/stats' },
			{ label: 'Moderation', icon: renderIcon(IconSword), path: '/dashboard/commands/moderation' },
			{ label: 'Songs', icon: renderIcon(IconPlaylist), path: '/dashboard/commands/songs' },
			{ label: 'Manage', icon: renderIcon(IconClipboardCopy), path: '/dashboard/commands/manage' },
		],
	},
	{
		label: 'Community',
		icon: renderIcon(IconUsers),
		children: [
			{ label: 'Users', icon: renderIcon(IconUsers), path: '/dashboard/community/users' },
			{ label: 'Roles', icon: renderIcon(IconShieldHalfFilled), path: '/dashboard/community/roles' },
		],
	},
	{
		label: 'Timers',
		icon: renderIcon(IconClockHour7),
		path: '/dashboard/timers',
	},
	{
		label: 'Moderation',
		icon: renderIcon(IconSword),
		path: '/dashboard/moderation' },
	{
		label: 'Keywords',
		icon: renderIcon(IconKey),
		path: '/dashboard/keywords' },
	{
		label: 'Variables',
		icon: renderIcon(IconActivity),
		path: '/dashboard/variables' },
	{
		label: 'Greetings',
		icon: renderIcon(IconSpeakerphone),
		path: '/dashboard/greetings',
	},
	{
		type: 'divider',
	},
].map((item) => ({
	...item,
	key: item.path ?? item.label,
	label: !item.path ? item.label ?? undefined : () => h(
		RouterLink,
		{
			to: {
				path: item.path,
			},
		},
		{ default: () => item.label },
	),
	children: item.children?.map((child) => ({
		...child,
		key: child.path,
		label: () => h(
			RouterLink,
			{
				to: {
					path: child.path,
				},
			},
			{ default: () => child.label },
		),
	})),
}));

const router = useRouter();

onMounted(async () => {
	await router.isReady();
	activeKey.value = router.currentRoute.value.path;
});

</script>

<template>
  <div style="display: flex; flex-direction: column; justify-content: space-between; height: calc(100vh - 43px)">
    <n-menu
      v-model:value="activeKey"
      :collapsed-width="64"
      :collapsed-icon-size="22"
      :options="menuOptions"
    />

    <n-menu
      :options="[{
        label: 'Logout',
        key: 'logout',
        onClick: () => {
          window.location.href = '/logout';
        },
      }]"
    >
    </n-menu>
  </div>
</template>

<style scoped>

</style>

// frontend/dashboard/components/layout/sidebar.tsx
import {
  Avatar,
  Box,
  createStyles,
  Group,
  Navbar,
  NavLink,
  ScrollArea,
  Text,
  UnstyledButton,
  useMantineTheme,
  Button,
  Divider,
  Loader,
} from '@mantine/core';
import { useViewportSize } from '@mantine/hooks';
import { useSpotlight } from '@mantine/spotlight';
import {
  IconActivity,
  IconBox,
  IconCalendarEvent,
  IconClipboardCopy,
  IconClockHour7,
  IconCommand,
  IconDashboard,
  IconDeviceDesktop,
  IconDeviceDesktopAnalytics,
  IconExternalLink,
  IconHeadphones,
  IconKey,
  IconPencilPlus,
  IconPlayerPlay,
  IconPlaylist,
  IconSettings,
  IconShieldHalfFilled,
  IconSpeakerphone,
  IconSword,
  IconUsers,
  TablerIcon,
} from '@tabler/icons';
import { useTranslation } from 'next-i18next';
import { useRouter } from 'next/router';
import { useCallback, useContext, useEffect, useState } from 'react';

import { resolveUserName } from '../../util/resolveUserName';

import { Dashboard, useDashboards, useProfile } from '@/services/api';
import { useLocale } from '@/services/dashboard';
import { SelectedDashboardContext } from '@/services/selectedDashboardProvider';

type Page = {
  label: string;
  icon?: TablerIcon;
  path: string;
  subPages?: Page[];
};

const navigationLinks: Array<Page | null> = [
  { label: 'Dashboard', icon: IconDashboard, path: '/' },
  { label: 'Integrations', icon: IconBox, path: '/integrations' },
  { label: 'Events', icon: IconCalendarEvent, path: '/events' },
  { label: 'Overlays', icon: IconDeviceDesktop, path: '/overlays' },
  {
    label: 'Song Requests',
    icon: IconHeadphones,
    path: '/song-requests',
    subPages: [
      { label: 'Player', icon: IconPlayerPlay, path: '/song-requests/player' },
      { label: 'Settings', icon: IconSettings, path: '/song-requests/settings' },
    ],
  },
  {
    label: 'Commands',
    icon: IconCommand,
    path: '/commands',
    subPages: [
      { label: 'Custom', icon: IconPencilPlus, path: '/commands/custom' },
      { label: 'Stats', icon: IconDeviceDesktopAnalytics, path: '/commands/stats' },
      { label: 'Moderation', icon: IconSword, path: '/commands/moderation' },
      { label: 'Songs', icon: IconPlaylist, path: '/commands/songs' },
      { label: 'Manage', icon: IconClipboardCopy, path: '/commands/manage' },
      // { label: 'Dota', path: '/commands/dota' },
    ],
  },
  {
    label: 'Community',
    icon: IconUsers,
    path: '/community',
    subPages: [
      { label: 'Users', icon: IconUsers, path: '/community/users' },
      { label: 'Roles', icon: IconShieldHalfFilled, path: '/community/roles' },
    ],
  },
  { label: 'Timers', icon: IconClockHour7, path: '/timers' },
  { label: 'Moderation', icon: IconSword, path: '/moderation' },
  { label: 'Keywords', icon: IconKey, path: '/keywords' },
  { label: 'Variables', icon: IconActivity, path: '/variables' },
  { label: 'Greetings', icon: IconSpeakerphone, path: '/greetings' },
  null,
];

type Props = {
  opened: boolean;
  setOpened: React.Dispatch<React.SetStateAction<boolean>>;
};

const useStyles = createStyles((theme) => ({
  link: {
    borderLeft: `1px solid ${
      theme.colorScheme === 'dark' ? theme.colors.dark[4] : theme.colors.gray[3]
    }`,
  },
}));

export function SideBar(props: Props) {
  const { classes } = useStyles();
  const { locale } = useLocale();
  const viewPort = useViewportSize();
  const router = useRouter();
  const theme = useMantineTheme();
  const { t } = useTranslation('layout');

  const { data: user } = useProfile();
  const { data: dashboards, isLoading } = useDashboards();

  const [selectedDashboard, setSelectedDashboard] = useState<Dashboard>();
  const spotlight = useSpotlight();
  const dashboardContext = useContext(SelectedDashboardContext);

  useEffect(() => {
    if (!user || !dashboards || !dashboardContext.id) return;
    const dashboard = dashboards.find((d) => d.id === dashboardContext.id);
    setSelectedDashboard(dashboard);
  }, [user, dashboards, dashboardContext.id]);

  const openSpotlight = useCallback(() => {
    if (!dashboards) return;

    if (user && dashboardContext.id) {
      spotlight.removeActions(spotlight.actions.map((a) => a.id!));

      const actions = dashboards.map((d) => ({
        title: resolveUserName(d.name, d.displayName),
        description: d.id,
        onTrigger: () => {
          setSelectedDashboard(dashboards.find((dash) => dash.id === d.id));
          dashboardContext.setId(d.id);
        },
        icon: <Avatar radius="xs" src={d.avatar} />,
        id: d.id,
      }));

      spotlight.registerActions(actions);
      spotlight.openSpotlight();
    }
  }, [dashboards]);

  const computeActive = (item: Page) => {
    if (item.subPages) {
      return router.asPath.startsWith(item.path);
    } else {
      return item.path === router.asPath;
    }
  };

  const createNavLink = (item: Page, isSubPage = false) => (
    <NavLink
      key={item.label}
      active={computeActive(item)}
      label={item.label}
      className={isSubPage ? classes.link : ''}
      defaultOpened={item.subPages && router.asPath.startsWith(item.path)}
      icon={item.icon ? <item.icon size={16} stroke={1.5} /> : ''}
      sx={{ width: '100%' }}
      component="a"
      href={`/dashboard/${locale}${item.path ? item.path : item.label.toLowerCase()}`}
      onClick={(e) => {
        e.preventDefault();
        if (item.subPages) return;
        props.setOpened(false);
        router.push(item.path ? item.path : item.label.toLowerCase(), undefined, { locale });
      }}
    >
      {item.subPages && item.subPages.map((p) => createNavLink(p, true))}
    </NavLink>
  );

  const [links, setLinks] = useState<JSX.Element[]>([]);
  useEffect(() => {
    setLinks(
      navigationLinks.map((item, i) => {
        return item === null ? <Divider key={i} /> : createNavLink(item);
      }),
    );
  }, [router]);

  return (
    <Navbar zIndex={99} hiddenBreakpoint="sm" hidden={!props.opened} width={{ sm: 250 }}>
      <Navbar.Section grow>
        <ScrollArea.Autosize
          maxHeight={viewPort.height - 170}
          type="auto"
          offsetScrollbars={true}
          styles={{
            viewport: {
              padding: 0,
            },
          }}
        >
          <Box component={ScrollArea} sx={{ width: '100%' }}>
            {links}
          </Box>
        </ScrollArea.Autosize>
      </Navbar.Section>
      <Navbar.Section>
        <Box
          sx={{
            padding: theme.spacing.sm,
            borderTop: `1px solid ${
              theme.colorScheme === 'dark' ? theme.colors.dark[4] : theme.colors.gray[2]
            }`,
          }}
        >
          {!isLoading && (
            <UnstyledButton
              sx={{
                display: 'block',
                width: '100%',
                padding: theme.spacing.xs,
                borderRadius: theme.radius.sm,
                color: theme.colorScheme === 'dark' ? theme.colors.dark[0] : theme.black,

                '&:hover': {
                  backgroundColor:
                    theme.colorScheme === 'dark' ? theme.colors.dark[6] : theme.colors.gray[0],
                },
              }}
              onClick={openSpotlight}
            >
              <Group>
                <Avatar src={selectedDashboard?.avatar} radius="xl" />
                <Box sx={{ flex: 1 }}>
                  <Text size="xs" weight={500}>
                    {t('sidebar.manage')}
                  </Text>
                  <Text color="dimmed" size="xs">
                    {selectedDashboard
                      ? resolveUserName(selectedDashboard.name, selectedDashboard.displayName)
                      : ''}
                  </Text>
                </Box>
              </Group>
            </UnstyledButton>
          )}
          {isLoading && <Loader color="violet" variant="dots" size={50} />}
          <Button
            size={'xs'}
            compact
            color="grape"
            style={{ marginTop: 5 }}
            variant={'light'}
            component="a"
            href={
              'window' in globalThis && selectedDashboard?.name
                ? `${window.location.origin}/p/${selectedDashboard?.name}/commands`
                : ''
            }
            target={'_blank'}
            leftIcon={<IconExternalLink size={14} />}
            w={'100%'}
          >
            Public page
          </Button>
        </Box>
      </Navbar.Section>
    </Navbar>
  );
}
