// apps/frontend/src/pages/Integrations.vue
<script lang="ts" setup>
import { useDisplay } from 'vuetify';

import DonationAlerts from '@/components/integrations/donationalerts.vue';
import Faceit from '@/components/integrations/faceit.vue';
import Lastfm from '@/components/integrations/lastfm.vue';
import Spotify from '@/components/integrations/spotify.vue';
import Streamlabs from '@/components/integrations/streamlabs.vue';
import VK from '@/components/integrations/vk.vue';

const { smAndDown } = useDisplay();
</script>

<template>
  <div>
    <v-row justify="center">
      <v-col :cols="smAndDown ? 12 : 3">
        <Spotify />
      </v-col>
      <v-col :cols="smAndDown ? 12 : 3">
        <VK />
      </v-col>
      <v-col :cols="smAndDown ? 12 : 3">
        <Lastfm />
      </v-col>
    </v-row>
    <v-row justify="center">
      <v-col :cols="smAndDown ? 12 : 3">
        <Faceit />
      </v-col>
      <v-col :cols="smAndDown ? 12 : 3">
        <Streamlabs />
      </v-col>
      <v-col :cols="smAndDown ? 12 : 3">
        <DonationAlerts />
      </v-col>
    </v-row>
  </div>
</template>

// apps/dashboard/pages/integrations.tsx
import { Grid } from '@mantine/core';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import { DonationAlertsIntegration } from '../components/integrations/donationalerts';
import { LastfmIntegration } from '../components/integrations/lastfm';
import { SpotifyIntegration } from '../components/integrations/spotify';
import { StreamlabsIntegration } from '../components/integrations/streamlabs';
import { VKIntegration } from '../components/integrations/vk';

import { FaceitIntegration } from '@/components/integrations/faceit';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
export const getServerSideProps = async ({ locale }) => ({
    props: {
        ...(await serverSideTranslations(locale, ['integrations', 'layout'])),
    },
});

const cols = {
  xs: 12,
  sm: 12,
  md: 5,
  lg: 5,
  xl: 5,
};

export default function Integrations() {
  return (
    <Grid justify="center">
      <Grid.Col {...cols}>
        <SpotifyIntegration />
      </Grid.Col>
      <Grid.Col {...cols}>
        <LastfmIntegration />
      </Grid.Col>
      <Grid.Col {...cols}>
        <VKIntegration />
      </Grid.Col>
      <Grid.Col {...cols}>
        <DonationAlertsIntegration />
      </Grid.Col>
      <Grid.Col {...cols}>
        <StreamlabsIntegration />
      </Grid.Col>
      <Grid.Col {...cols}>
        <FaceitIntegration />
      </Grid.Col>
    </Grid>
  );
}
