// frontend/dashboard/components/integrations/donateStream.tsx
import {
	ActionIcon,
	Alert,
	Anchor,
	Button,
	CopyButton,
	Stepper,
	Text,
	TextInput,
} from '@mantine/core';
import { showNotification } from '@mantine/notifications';
import { IconCopy, IconInfoCircle } from '@tabler/icons';
import { useTranslation } from 'next-i18next';
import { Fragment, useCallback, useEffect, useState } from 'react';

import { IntegrationCard } from './card';

import { useDonateStreamIntegration } from '@/services/api/integrations';

export default () => {
	const manager = useDonateStreamIntegration();
	const { data: apiKey } = manager.useData();
	const secretPost = manager.usePost();
	const { t: integrationsTranslate } = useTranslation('integrations');

	const [key, setKey] = useState<string>('');
	const [secret, setSecret] = useState<string>('');

	useEffect(() => {
		if (typeof apiKey !== 'undefined') {
			setKey(`${window.location.origin}/api/webhooks/integrations/donate-stream/${apiKey}`);
		}
	}, [apiKey]);

	const onSubmit = useCallback(() => {
		if (apiKey && secret) {
			secretPost.mutate({ id: apiKey, secret });
		}
	}, [apiKey, secret]);

	return (
		<IntegrationCard title="Donate.stream">
			<Stepper active={0} allowNextStepsSelect={false} orientation="vertical">
				<Stepper.Step
					label="Step 1"
					description={
						<Fragment>
							Paste that link into input on the{' '}
							<Anchor href={'https://lk.donate.stream/settings/api-key'} target={'_blank'}>
								https://lk.donate.stream/settings/api
							</Anchor>{' '}
							page
							<TextInput
								mt={5}
								value={key}
								onChange={() => {}}
								variant={'filled'}
								rightSection={
									<CopyButton value={key!}>
										{({ copy }) => (
											<ActionIcon
												onClick={() => {
													copy();
													showNotification({
														color: 'green',
														title: 'Copied',
														message: 'Copied to clipboard',
													});
												}}
											>
												<IconCopy />
											</ActionIcon>
										)}
									</CopyButton>
								}
							/>
						</Fragment>
					}
				/>
				<Stepper.Step
					label="Step 2"
					description={
						<Fragment>
							Paste the{' '}
							<Anchor href={'https://i.imgur.com/OtW97pV.png'} target={'_blank'}>
								secret key
							</Anchor>{' '}
							from page and click button for save
							<TextInput
								mt={5}
								value={secret}
								placeholder={'paste secret here'}
								onChange={(e) => setSecret(e.target.value)}
								variant={'filled'}
							/>
							<Button mt={5} size={'sm'} color={'green'} variant={'light'} onClick={onSubmit}>
								Send
							</Button>
						</Fragment>
					}
				/>
				<Stepper.Step
					label="Step 3"
					description={'Back to donate.stream and click "confirm" button'}
				/>
			</Stepper>

			<Alert color={'lime'} icon={<IconInfoCircle />} mt={5}>
				<Text dangerouslySetInnerHTML={{ __html: integrationsTranslate('info.donations') }} />
			</Alert>
		</IntegrationCard>
	);
};

// frontend/dashboard-new/src/components/integrations/donatestream.vue
<script setup lang='ts'>
import { NTimeline, NTimelineItem, NText, NInput, NButton, NInputGroup } from 'naive-ui';
import { computed, ref } from 'vue';

import { useDonateStreamIntegration } from '@/api/index.js';
import DonateStreamSVG from '@/assets/icons/integrations/donate.stream.svg';
import CopyInput from '@/components/copyInput.vue';
import WithSettings from '@/components/integrations/variants/withSettings.vue';

const integration = useDonateStreamIntegration();
const { data } = integration.useGetData();
const { mutateAsync } = integration.usePost();

const currentPageUrl = `${window.location.origin}/api/webhooks/integrations/donatestream`;
const webhookUrl = computed(() => {
	return `${currentPageUrl}/${data.value?.integrationId}`;
});

const secret = ref('');
async function saveSecret() {
	console.log(secret.value);
	if (!secret.value) return;
	await mutateAsync(secret.value);
}
</script>

<template>
  <with-settings name="Donate.stream">
    <template #icon>
      <DonateStreamSVG style="width: 50px" />
    </template>
    <template #settings>
      <n-timeline>
        <n-timeline-item type="info" title="Step 1">
          <n-text>
            Paste that link into input on the
            <a
              href="https://lk.donate.stream/settings/api"
              target="_blank"
              class="link"
            >
              https://lk.donate.stream/settings/api
            </a>
            <copy-input :text="webhookUrl" style="margin-top: 5px" />
          </n-text>
        </n-timeline-item>
        <n-timeline-item type="info" title="Step 2">
          <n-text>
            Paste the <a
              href="https://i.imgur.com/OtW97pV.png"
              target="_blank"
              class="link"
            >
              secret key
            </a>
            from page and click SAVE
          </n-text>
          <n-input-group>
            <n-input v-model:value="secret" type="text" size="small" placeholder="secret from page" />
            <n-button size="small" secondary type="success" @click="saveSecret">
              Save
            </n-button>
          </n-input-group>
        </n-timeline-item>
        <n-timeline-item type="info" title="Step 3">
          <n-text>Back to donate.stream and click "confirm" button</n-text>
        </n-timeline-item>
      </n-timeline>
    </template>
  </with-settings>
</template>

<style scoped>
.link {
	color: #41c489;
	text-decoration: none
}
</style>
