// frontend/dashboard/components/integrations/oauthComponent.tsx
import { Avatar, Badge, Button, Flex, Text, Tooltip } from '@mantine/core';
import { IconLogin, IconLogout } from '@tabler/icons';
import { useTranslation } from 'next-i18next';
import Image from 'next/image';
import { forwardRef } from 'react';

type Props = {
	integrationKey: string
	profile?: {
		avatar?: string,
		name?: string,
	}
	login: () => void | Promise<void>
	logout: () => void | Promise<void>
}

export const OAuthComponent: React.FC<Props> = (props) => {
	const { t } = useTranslation('integrations');

	return <tr key={props.integrationKey} style={{ height: 65 }}>
		<td><Image
			src={`/dashboard/assets/icons/brands/${props.integrationKey}.svg`}
			height={30}
			width={30}
			alt={props.integrationKey}
		/>
		</td>
		<td>
			{props.profile
				? <Flex direction={'row'} align='center'>
					<Avatar
						src={props.profile.avatar}
						h={30}
						w={30}
						style={{ borderRadius: 111 }}
					/>
					<Text size={30} ml={10}>
						{props.profile.name}
					</Text>
				</Flex>
				: <Badge>Not logged in</Badge>
			}
		</td>
		<td>
			<Flex direction='row' gap='sm' justify='flex-end'>
				{props.profile && (
					<Button
						compact
						leftIcon={<IconLogout />}
						variant='light'
						color='red'
						onClick={() => props.logout()}
					>
						{t('logout')}
					</Button>
				)}
				<Button compact leftIcon={<IconLogin />} variant='light' color='green' onClick={props.login}>
					{t('login')}
				</Button>
			</Flex>
		</td>
	</tr>;
};

// frontend/dashboard-new/src/components/integrations/oauthComponent.vue
<script setup lang='ts'>
import { IconLogin, IconLogout } from '@tabler/icons-vue';
import { NButton, NTooltip, NAvatar } from 'naive-ui';
import type { FunctionalComponent } from 'vue';
import { defineSlots } from 'vue';

const props = defineProps<{
	name: string,
	data: { userName: string, avatar: string } | undefined
	logout: () => Promise<void>
	getLoginLink: () => Promise<{ data: { link: string } }>
}>();

defineSlots<{
	icon: FunctionalComponent<any>
}>();

async function login() {
	const req = await props.getLoginLink();
	if (!req.data?.link) return;
	window.location.replace(req.data?.link);
}
</script>

<template>
  <tr>
    <td>
      <n-tooltip trigger="hover" placement="left">
        <template #trigger>
          <slot name="icon" />
        </template>
        {{ name }}
      </n-tooltip>
    </td>
    <td>
      <div v-if="data?.userName" class="profile">
        <n-avatar :src="data.avatar" class="avatar" round />
        <n-text>
          {{ data.userName }}
        </n-text>
      </div>
      <span v-else class="badge">Not Logged In</span>
    </td>
    <td>
      <div class="actions">
        <n-button strong secondary type="error" @click="logout">
          <IconLogout />
          Logout
        </n-button>
        <n-button trong secondary type="success" @click="login">
          <IconLogin />
          Login
        </n-button>
      </div>
    </td>
  </tr>
</template>

<style scoped>
.badge {
	background-color: #59c4c3;
	color: #0a0a0a;
	padding: 5px 10px;
	border-radius: 5px;
	font-size: 12px;
	font-weight: 500;
}

.actions {
	display: flex;
	justify-content: flex-end;
	align-items: center;
	gap: 5px;
	width: auto;
}

.profile {
	display: flex;
	align-items: center;
	gap: 5px;
}
</style>
