// frontend/landing/src/components/login.tsx
import { useEffect, useState } from 'preact/compat';

import { browserUnProtectedClient } from '../api/twirp-browser.js';

export default () => {
	const [error, setError] = useState('');

	useEffect(() => {
		const url = new URL(window.location.href);
		const code = url.searchParams.get('code');
		const err = url.searchParams.get('error');
		if (err) {
			setError(err);
		} else {
			browserUnProtectedClient.authPostCode({
				code,
			})
				.then(() => window.location.replace('/dashboard'))
				.catch(() => setError('internal error'));
		}
	}, []);

	return <>
	Login
	{error}
</>;
};

// frontend/landing/src/pages/login.vue
<script lang="ts" setup>
// import { unProtectedClient } from "../api/twirp.js";

// const url = new URL(Astro.request.url)
// const code = url.searchParams.get('code')
// let error = url.searchParams.get('error')

// if (code) {
// 	try {
// 		await unProtectedClient.authPostCode({
// 			code,
// 		})
// 	} catch (e) {
// 		console.error(e)
// 		error = 'internal error'
// 	}
// }
</script>

<template>
	{{ window.location.origin }}
</template>
